services:
  noterain:
    image: git.donnerdachs.com/s/noterain:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      FORCE_HTTP: "true"
      PORT: "3000"
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./client/public/samples:/app/dist/client/samples:ro
