version: "3.3"

services:
  noterain:
    build: .
    ports:
      - "3001:3000"
    environment:
      - FORCE_HTTP=true
      - PORT=3000
    volumes:
      - ./client/public/samples:/app/dist/client/samples:ro
    restart: unless-stopped
